name: "Continous Deployment"
on:
  release:
    type: [released]
jobs:
  publish_docker:
    name: Publish Docker
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Git
        uses: actions/checkout@v2.3.4

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Inject Github Variables
        uses: rlespinasse/github-slug-action@v3.x

      - name: Install Nix
        uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Build and Push Docker
        run: nix-shell shells.nix -A docker-cicd --run ./scripts/ci/docker-cd.sh
        env:
          DOMAIN: docker.pkg.github.com
          GITHUB_REPO_REF: ${{ github.repository }}
          GITHUB_TAG: ${{ github.refs }}

          CI_DOCKER_IMAGE: nix-ci
          CI_DOCKER_CONTEXT: .
          CI_DOCKER_FILE: Dockerfile

          EXTERNAL_IMAGE_NAME: kirinnee/nix-ci-sample

          GITHUB_DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_DOCKER_USER: ${{ github.actor }}
          EXTERNAL_DOCKER_PASSWORD: ${{ secrets.DOCKER_TOKEN }}
          EXTERNAL_DOCKER_USER: ${{ secrets.DOCKER_USER }}
