name: "Continous Integration"
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  precommit:
    name: Pre-Commit
    runs-on: ubuntu-20.04
    steps:
      - name: AtomiCloud CI Environment
        uses: kirinnee/atomici-action@v1.0.2

      - name: Use Cachix
        run: cachix use kirinnee-sample-binary-cache

      - name: Checkout Code
        uses: actions/checkout@v2.3.4

      - name: Run Pre-commit checks
        run: nix-shell nix/shells.nix -A lint-ci --run scripts/ci/pre-commit.sh

  build_docker:
    name: Build Docker
    runs-on: ubuntu-20.04
    steps:
      - name: AtomiCloud CI Environment
        uses: kirinnee/atomici-action@v1.0.2

      - name: Checkout Git
        uses: actions/checkout@v2.3.4

      - name: Inject Github Variables
        uses: rlespinasse/github-slug-action@v3.x

      - name: Build and Push Docker
        run: nix-shell nix/shells.nix -A docker-cicd --run scripts/ci/docker-ci.sh
        env:
          DOMAIN: docker.pkg.github.com
          GITHUB_REPO_REF: ${{ github.repository }}
          GITHUB_SHA: ${{ github.sha }}
          GITHUB_BRANCH: ${{ env.GITHUB_REF_SLUG }}

          CI_DOCKER_IMAGE: nix-ci
          CI_DOCKER_CONTEXT: .
          CI_DOCKERFILE: Dockerfile

          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_USER: ${{ github.actor }}
