name: Release
on:
  push:
    branches:
      - main
    tags-ignore:
      - v*.*.*
jobs:
  release:
    name: Release
    runs-on: ubuntu-20.04
    steps:
      - name: AtomiCloud CI Environment
        uses: kirinnee/atomici-action@v2.1.0
        with:
          binary_cache: kirinnee-sample-binary-cache

      - name: Checkout Code
        uses: actions/checkout@v2.3.4
        with:
          persist-credentials: false

      - name: Remove GitHooks
        run: rm ./.git/hooks/*

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: nix-shell nix/shells.nix -A releaser --run scripts/ci/release.sh
