name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Release
    runs-on: ubuntu-20.04
    steps:
      - name: AtomiCloud CI Environment
        uses: kirinnee/atomici-action@v1.1.0

      - name: Use Cachix
        run: cachix use kirinnee-sample-binary-cache

      - name: Checkout Git
        uses: actions/checkout@v2.3.4
        with:
          persist-credentials: false

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: nix-shell nix/shells.nix -A releaser --run scripts/ci/release.sh
